# Basic
title: VPNPro 在线文档
subtitle: 突破IP限制，访问全球资源
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">文档目录</a>
#description: Vno Jekyll is a port of my Ghost theme vno.
#creator: <a href="http://onev.cat">@onevcat</a>

url: "https://docs.vpnpro.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 教程
    description: 在线教程

# Navigation buttons in the front page.
nav:
    - {title: 主页, description: VPN Pro 主页, url: 'https://www.vpnpro.me'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: VPNPro
    # duoshuo: 
    
# Social
social:
    facebook: daigang0701@gmail.com
    github: ddxs
    twitter: daigang0701@gmail.com
    gplus: daigang0701@gmail.com
    mail: support@vpnpro.me

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
